// auth
export const SIGN_IN = 'SIGN_IN'
export const SIGN_IN_FAIL = 'SIGN_IN_FAIL'
export const SIGN_UP = 'SIGN_UP'
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export const RESET_PASSWORD = 'RESET_PASSWORD'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL'

// shop
export const FETCH_PHOTOS = 'FETCH_PHOTOS'
export const FETCH_PHOTOS_SUCCESS = 'FETCH_PHOTOS_SUCCESS'
export const FETCH_PHOTOS_FAIL = 'FETCH_PHOTOS_FAIL'
export const ADD_CART_ITEM = 'ADD_CART_ITEM'
export const DELETE_CART_ITEM = 'DELETE_CART_ITEM'
export const RESET_PHOTOS = 'RESET_PHOTOS'